select
so.bossprimary, so.sdssprimary,so.scienceprimary,
sp.specObjID, sp.objid, so.specObjID,
so.mjd, so.plate, so.fiberID, so.run2d,
sp.ra,sp.dec,sp.z,
sp.class,so.zwarning,
so.programname,so.instrument,so.survey,
so.boss_target1, so.eboss_target1,
xm.match_dist AS match_dist,
sp.cmodelmag_u AS cmod_u,
sp.cmodelmag_g AS cmod_g,
sp.cmodelmag_r AS cmod_r,
sp.cmodelmag_i AS cmod_i,
sp.cmodelmag_z AS cmod_z,
sp.cmodelmagerr_u AS cmoderr_u,
sp.cmodelmagerr_g AS cmoderr_g,
sp.cmodelmagerr_r AS cmoderr_r,
sp.cmodelmagerr_i AS cmoderr_i,
sp.cmodelmagerr_z AS cmoderr_z,
sp.psfmag_u AS psf_u,
sp.psfmag_g AS psf_g,
sp.psfmag_r AS psf_r,
sp.psfmag_i AS psf_i,
sp.psfmag_z AS psf_z,
sp.psfmagerr_u AS psferr_u,
sp.psfmagerr_g AS psferr_g,
sp.psfmagerr_r AS psferr_r,
sp.psfmagerr_i AS psferr_i,
sp.psfmagerr_z AS psferr_z,
sp.extinction_u AS ext_u,
sp.extinction_g AS ext_g,
sp.extinction_r AS ext_r,
sp.extinction_i AS ext_i,
sp.extinction_z AS ext_z,  
w.w1mpro AS w1,
w.w2mpro AS w2,
w.w3mpro AS w3,
w.w4mpro AS w4,
w.w1sigmpro AS w1err,
w.w2sigmpro AS w2err,
w.w3sigmpro AS w3err,
w.w4sigmpro AS w4err,
from SpecPhoto AS sp
JOIN SpecObj as so ON sp.specobjid = so.specobjid
JOIN wise_xmatch AS xm ON sp.objid = xm.sdss_objid
JOIN wise_allsky AS w ON xm.wise_cntr = w.cntr
